### ISSUE TITLE
themes not looking the way they should

### ISSUE THREAD

**Issue by Tervicke** [erikdubois/Plank-Themes#2]
i dont know why most of my themes are not working i am on lubuntu 20.10 and almost all of my themes i tried the theme that u are using (Mint-Y )but its doesnt look as its seen in your 
![screen01](https://user-images.githubusercontent.com/77972850/119251227-378df880-bbc3-11eb-9fd0-12f7930d276a.jpg)

**Comment by erikdubois** [comment]
a virtual machine will not display transparency

**Comment by Tervicke** [comment]
i am not using a virtual machine?
